version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run: docker build -t vim8 .
      - run: docker image list
